name: 'discord-action-embed'
description: 'Send a message to a Discord webhook with embed.'
branding:
  color: 'purple'
  icon: 'message-square'
inputs:
  webhook:
    description: 'Discord webhook URL'
    required: true
  message:
    description: 'Message to be sent'
    required: true
  embed:
    description: 'Embed details to be sent'
    required: false
runs:
  using: 'node12'
  main: 'index.js'